spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
      url: 'jdbc:h2:file:/Users/Piotrek/IdeaProjects/ListaZadanSpring/ListaZadan-db'
  jpa:
    hibernate:
      ddl-auto: update

task.template.allowMultipleTasksFromTemplate: false



