spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
      url: 'jdbc:h2:file:/Users/Piotrek/IdeaProjects/ListaZadanSpring/ListaZadan-db'
  jpa:
    hibernate:
      ddl-auto: validate

task.template.allowMultipleTasksFromTemplate: false

management:
  endpoints:
    jmx:
      exposure:
        include: '*'


